name: Docker
run-name: Docker image creation
on:
  workflow_dispatch:
env:
  DOCKER_IMAGE_BASE: ghcr.io/jaumoso/web-exif
  DOCKER_IMAGE_TAG: latest
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: "1"

      - name: Create Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_BASE }}:${{ env.DOCKER_IMAGE_TAG }} .

      - name: Publish images
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u Jaumoso --password-stdin
          docker push ${{ env.DOCKER_IMAGE_BASE }}:${{ env.DOCKER_IMAGE_TAG }}
